### ISSUE TITLE
Maths may be wrong.

### ISSUE THREAD

**Issue by discochuck** [gruvin/hexmob.win#21] opened 2022-02-03 22:59 UTC
I always hate bothering ya, but clearly not enough to stop posting issues on github. 

Im not sure exactly where the issue came into play, but i think the maths got messed up in one of the recent updates. 

might have been in the "USD Value Total and USD Penalty now include include BPD correctly" commit? tho i checked the diff and it looks like nothing changing mathematically, but i am far from an expert. 

![Screenshot 2022-02-03 165347](https://user-images.githubusercontent.com/1681165/152442791-f2a80ea8-f055-488b-a7ca-df388a08e75f.png)

Looks like there's a period instead of a comma in the image below specifically the interest field. 

hex.com
-----
![Screenshot 2022-02-03 165457](https://user-images.githubusercontent.com/1681165/152442938-66cd61ab-7f5a-4186-b531-fc35ba4defea.png)

tshare.app
----
![Screenshot 2022-02-03 165211](https://user-images.githubusercontent.com/1681165/152442663-bb768d9c-df2e-4407-aa0e-bffcd962c293.png)

Hope this Issue submission finds you well. 

Take care,
-discochuck

**Comment by gruvin** [comment] 2022-02-04 01:46
Well firstly, thanks for letting me know. I actually might have seen this myself a couple days ago but completely forgot to follow up. Dangit.

The only change was to try and work around the bug in Apple's websocket protocol shite to grab data in smaller chunks and thus avoid the error. Turns out even that only barely works and will probably break for stakes having run for more than some number of days.

In any case, I guess we're just not getting the error --OR-- all the data now. Cannot sum daily payout figures that never arrived. This means I should make the code check that the expected number of days worth of data was in fact received.

I'm having a go now.

**Comment by gruvin** [comment] 2022-02-04 10:13
I've confirmed that the Apple issue (failed in any case) "fix" is the culprit. Hopefully I'll figure it out and fixed (or just reverted) tomorrow. It really would be nice to find a definitive way around the stupid Apple thing. It's been highly depressing and demotivating, being as there's nothing I can do about it and Apple is remaining silent about it across all forums known to me. (Many others are having the same issue. It's not just us.)

**Comment by gruvin** [comment] 2022-02-05 00:04
Fixed in v0.2.63B. Thanks again!

**Closed as completed by gruvin** 2022-02-05 00:04 UTC
